<?php

/*
function changes_theme($existing, $type, $theme, $path) {
  return array(
    'changes_diff' => array(
      'variables' => [
        'left_revision' => NULL,
        'right_revision' => NULL,
        'changed_items' =>
      ],
    ),
  );
}

function template_preprocess_changes_diff(&$variables) {
  $context = ['view_mode' => $variables['view_mode']];
  $comment_links = \Drupal::service('comment.link_builder')->buildCommentedEntityLinks($variables['discussion'], $context);
  $variables['ahs_new_comments'] = [
    '#type' => 'link',
    '#title' => $comment_links['comment__field_comments_with_changes']['#links']['comment-new-comments']['title'],
    '#url' => $comment_links['comment__field_comments_with_changes']['#links']['comment-new-comments']['url'],
    '#attributes'=> $comment_links['comment__field_comments_with_changes']['#links']['comment-new-comments']['attributes'],
    '#cache' => $comment_links['comment__field_comments_with_changes']['#cache'],
    '#attached' => $comment_links['comment__field_comments_with_changes']['#attached'],
  ];

  // Class is not an array, needs to be made into one
  if (isset($variables['ahs_new_comments']['#attributes']['class']) &&
    !is_array($variables['ahs_new_comments']['#attributes']['class'])) {
    $variables['ahs_new_comments']['#attributes']['class'] = [$variables['ahs_new_comments']['#attributes']['class']];
  }
  // Make it a bootstrap label
  $variables['ahs_new_comments']['#attributes']['class'][] = 'ahs-new';
  $variables['ahs_new_comments']['#attributes']['class'][] = 'label';
  $variables['ahs_new_comments']['#attributes']['class'][] = 'label-success';
}
*/

/*
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\RevisionableInterface;
use Drupal\field\Entity\FieldStorageConfig;

function changes_entity_update(Drupal\Core\Entity\EntityInterface $entity) {

  // Skip if this is not a new revision
  if ($entity instanceof RevisionableInterface) {
    $oldRevisionId = $entity->original->getRevisionId();
    $newRevisionId = $entity->getRevisionId();
    if ($oldRevisionId != $newRevisionId) {
      
      // Find comment fields
      $entityFieldDefinitions = $entity->getFieldDefinitions();
      foreach ($entityFieldDefinitions as $entityFieldDefinition) {
        
        // Check every comment field
        if ($entityFieldDefinition->getType() === 'comment') {
          $commentFieldName = $entityFieldDefinition->getName();
          $commentFieldStorage = FieldStorageConfig::loadByName($entity->getEntityType()
            ->id(), $commentFieldName);
          $commentType = $commentFieldStorage->getSetting('comment_type');
          $commentFieldDefinitions = \Drupal::entityManager()
            ->getFieldDefinitions('comment', $commentType);
          
          // See if the comment field has a diff field on its chosen comment type
          foreach ($commentFieldDefinitions as $commentFieldDefinition) {
            if ($commentFieldDefinition->getType() === 'changes') {
              
              // Make a comment about the changes
              $diffFieldName = $commentFieldDefinition->getName();
              $comment = [
                'comment_type' => $commentType,
                'field_name' => $commentFieldName,
                'subject' => 'Change record',
              ];
              \Drupal::service('changes.comment_with_changes')
                ->add($comment, $entity, $oldRevisionId, $newRevisionId, $diffFieldName);
            }
          }
        }
      }
    }
  }

}
*/
