# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The runtime the application uses.
type: "php:5.6"

# Configuration of the build of this application.
build:
    flavor: drupal

# The build-time dependencies of the app
dependencies:
    php:
        "drush/drush": "8.0.1"
        "drupal/console": "^0.10"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"
#    solr: "solr:solr"
#    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        "/":
            # The folder to serve static assets for this location from.
            # (Relative to the application root.)
            root: "public"

            # How long to allow static assets from this location to be cached.
            # (Can be a time or -1 for no caching. Times can be suffixed with
            # "ms" (milliseconds), "s" (seconds), "m" (minutes), "h" (hours),
            # "d" (days), "w" (weeks), "M" (months, 30d) or "y" (years, 365d).)
            expires: -1

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # (Can be true, false or a URI path string.)
            passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/public/sites/default/files": "shared:files/files"
    "/tmp": "shared:files/tmp"
    "/private": "shared:files/private"
    "/drush-backups": "shared:files/drush-backups"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
       #cd ./public
       curl -sS https://getcomposer.org/installer | php
       composer require drupal/drupal-extension='~3.0'
       #composer require guzzlehttp/guzzle ='6.0.1'
       #composer config bin-dir= 'vendor/bin/'
       php composer.phar update
       #vendor/bin/behat --init
       #vendor/bin/behat -dl
       #vendor/bin/behat --init
       #vendor/bin/behat -dl
       

    # We run deploy hooks after your application has been deployed and started.
    deploy: |
      cd /app/public
      #drush -y site-install --site-name=drupal8 --account-name=admin --account-pass=password
      drush -y updatedb
      chmod -R 777 sites/default
      drush -y updatedb
      cd /app/public/sites/default
      cp deploy.php files/
      cp -r config/sync/. files/ahsweb/config/sync/
      drush -y config-import
      cd files
      rm -rf Behat_Testing/
      mkdir Behat_Testing
      chmod -R 777 Behat_Testing/
      cp -r /app/public/sites/default/BehatTest/. Behat_Testing/
      cp -r /app/public/sites/default/BehatFiles/. Behat_Testing/
      cd Behat_Testing/
      php composer.phar update
      bin/behat --init
      cp installaion.feature vendor/behat/behat/features/
      rm -rf vendor/behat/behat/features/bootstrap/FeatureContext.php
      cp FeatureContext.php vendor/behat/behat/features/bootstrap/
      cd /app/public/sites/default/files/Behat_Testing;
      cd vendor/behat/behat;
      #bin/behat features/installaion.feature --format progress --out features/my_behat_errors.txt
      $testResult=bin/behat features/installaion.feature
      
# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
