# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The runtime the application uses.
type: "php:5.6"


runtime:
   extensions:
      - imap

# Configuration of the build of this application.
build:
    flavor: drupal

# The build-time dependencies of the app.
# Note: Drush 7.0.0 (stable) is released, but it purposefully does not work
# with Drupal 8.
dependencies:
    php:
        "drush/drush": "8.0.0-rc1"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"
    solr: "solr:solr"
    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/"
    # The front-controller script to send non-static requests to.
    passthru: "/index.php"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/public/sites/default/files": "shared:files/files"
    #"/app/public/sites/default": "shared:files/app/public/sites/default"
    "/tmp": "shared:files/tmp"
    "/config": "shared:files/config"
    "/private": "shared:files/private"

# The hooks executed at various points in the lifecycle of the application.
hooks:
       

# We run deploy hook after your application has been deployed and started.


    build: |
       cd ./public
       php modules/composer_manager/scripts/init.php
       composer drupal-update
       composer update
       #composer require drupal/drupal-extension='~3.0'
       #vendor/bin/behat --init
       #vendor/bin/behat -dl
       #mv vendor/behatfiles/behat.yml vendor/behat/behat/behat.yml
       #mv vendor/behatfiles/*.feature vendor/behat/behat/features/

    deploy: |
      # Drupal 8 currently fails to create config directories
      # automatically during install.
      mkdir -p config/active config/staging
      cd public
      #drush -y site-install --site-name=drupal8 --account-name=admin --account-pass=password
      drush -y updatedb
      #chmod -R 777 sites/default
      #drush -y en advanced_help eck eform layout_plugin page_manager inmail mailmute token
      #drush -y en panels simplenews
      #drush -y en entity_reference_revisions paragraphs
      #drush -y pmu civicrm_views
      #drush -y pmu civicrm
      #drush -y en composer_manager
      #drush en -y flysystem flysystem_dropbox flysystem_s3
      #drush en -y jplayer
      #drush en -y image_title_caption
      #drush en -y media_player_module
      #drush en -y swiftmailer
      #drush en -y mailsystem
      #drush en -y filefield_sources
      #drush en -y filefield_sources_flysystem 
      #drush en -y media_entity
      #drush pmu -y media_pinkeye
      #drush en -y media_entity_embeddable_video media_entity_image media_entity_slideshow
      #drush en -y media_entity_twitter media_entity_instagram media_entity_audio
      #drush pmu -y media_entity
      #drush en -y media_entity_audio
      drush en -y media_pinkeye

# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
