<?php

use \Drupal\node\Entity\Node;
use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_install().
 *
 * Create the home page.
 */
/*
function ahs_miscellaneous_install() {
  // See if the home page already exists
  $query = \Drupal::entityQuery('node')
    ->condition('title', 'Home')
    ->condition('type', 'information');
  $nids = $query->execute();
  if (empty($nids)) {
    // It does not, so create it
    $node = Node::create([
      'type' => 'information',
      'title' => 'Home',
      'uid' => 1,
      'status' => 1,
      // Disable pathauto 'Generate automatic URL alias'
      // and use an alternative alias, so that we can use
      // the URL '/discuss' for something else.
      'path' => ['pathauto' => FALSE, 'alias' => '/home'],
    ]);
    $node->save();
  }
}
*/

/**
 * Implementation of hook_node_presave().
 *
 */
function ahs_miscellaneous_node_presave($node) {
  ahs_miscellaneous_node_title_sanitise($node);

}

/**
 * Implementation of hook_node_insert().
 *
 */
function ahs_miscellaneous_node_insert($node) {
  ahs_miscellaneous_event_session_correspond($node);
}

/**
 * Implementation of hook_node_update().
 *
 */
function ahs_miscellaneous_node_update($node) {
  ahs_miscellaneous_event_session_correspond($node);
}

/**
 * Enforce correspondence between events and sessions.
 *
 */
function ahs_miscellaneous_event_session_correspond($node) {
  if ($node->bundle() == 'event') {
    \Drupal::service('ahs_cer.simple_cer')
      ->updateReferences('field_sessions', 'field_event', $node);
  }
  if ($node->bundle() == 'session') {
    \Drupal::service('ahs_cer.simple_cer')
      ->updateReferences('field_event', 'field_sessions', $node);
  }
}

/**
 * Remove slashes and pretty up node titles.
 *
 */
function ahs_miscellaneous_node_title_sanitise($node) {
  $node->title->value = trim($node->title->value);

  // If title is all upper case and has multiple words,
  // assume the capitalisation is inappropriate
  if ((mb_strtoupper($node->title->value, 'utf-8') === $node->title->value) &&
    (strpos($node->title->value, " ") !== FALSE)) {
    $node->title->value = strtolower($node->title->value);
  }

  // Always capitalise the first letter
  $node->title->value = Unicode::ucfirst($node->title->value);

  // Replace slashes with a space
  $node->title->value = str_replace('/', ' ', $node->title->value);

  // replace 2 or more spaces with single space
  $node->title->value = $s = preg_replace("/ {2,}/", " ", $node->title->value);
}